// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | ImageGallerySlice
  | ImageWithTextSlice
  | IconWIthTextSlice
  | HeroBannerSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Age Verification documents
 */
interface AgeVerificationDocumentData {
  /**
   * Hide Module field in *Age Verification*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: age_verification.hide_module
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Background Image field in *Age Verification*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Color field in *Age Verification*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Heading field in *Age Verification*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *Age Verification*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.sub_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Agreement Text field in *Age Verification*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.agreement_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  agreement_text: prismic.RichTextField;

  /**
   * Age Number field in *Age Verification*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.age_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age_number: prismic.NumberField;

  /**
   * Logo field in *Age Verification*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * To Redirect field in *Age Verification*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: age_verification.to_redirect
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  to_redirect: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Age Verification document from Prismic
 *
 * - **API ID**: `age_verification`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AgeVerificationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AgeVerificationDocumentData>,
    "age_verification",
    Lang
  >;

/**
 * Item in *AnnouncementBar → Items*
 */
export interface AnnouncementBarDocumentDataItemsItem {
  /**
   * Icon field in *AnnouncementBar → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *AnnouncementBar → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon 2 field in *AnnouncementBar → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.items[].icon_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon_2: prismic.ImageField<never>;
}

/**
 * Content for AnnouncementBar documents
 */
interface AnnouncementBarDocumentData {
  /**
   * Hide Module field in *AnnouncementBar*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: announcement_bar.hide_module
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Background Color field in *AnnouncementBar*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Items field in *AnnouncementBar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<AnnouncementBarDocumentDataItemsItem>>;
}

/**
 * AnnouncementBar document from Prismic
 *
 * - **API ID**: `announcement_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AnnouncementBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AnnouncementBarDocumentData>,
    "announcement_bar",
    Lang
  >;

type BlogDocumentDataSlicesSlice = BlogCardsSlice | SliderSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Title Color field in *Blog*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Content Color field in *Blog*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.content_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_color: prismic.ColorField;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Category field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Content field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Shareable Links field in *Blog Post*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.shareable_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  shareable_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type ContainerDocumentDataSlicesSlice = SliderSlice;

/**
 * Content for Container documents
 */
interface ContainerDocumentData {
  /**
   * Slice Zone field in *Container*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: container.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContainerDocumentDataSlicesSlice>;
}

/**
 * Container document from Prismic
 *
 * - **API ID**: `container`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContainerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContainerDocumentData>,
    "container",
    Lang
  >;

/**
 * Item in *Footer → Footer Categories*
 */
export interface FooterDocumentDataFooterCategoriesItem {
  /**
   * Category Heading field in *Footer → Footer Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_categories[].category_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_heading: prismic.KeyTextField;

  /**
   * Category Link field in *Footer → Footer Categories*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_categories[].category_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Hide Module field in *Footer*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: footer.hide_module
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Background Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Color field in *Footer*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Footer Terms field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_terms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_terms: prismic.RichTextField;

  /**
   * Footer Warning field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_warning
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_warning: prismic.RichTextField;

  /**
   * Footer Categories field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_categories: prismic.GroupField<
    Simplify<FooterDocumentDataFooterCategoriesItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomeDocumentDataSlicesSlice =
  | FeaturedProductsSlice
  | NewsLetterSlice
  | ImageWithTextSlice
  | SliderSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LoyaltyDocumentDataSlicesSlice =
  | ImageWithTextSlice
  | LoyaltyCardsSlice
  | HeroBannerSlice;

/**
 * Content for Loyalty documents
 */
interface LoyaltyDocumentData {
  /**
   * Heading field in *Loyalty*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Title Color field in *Loyalty*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.title_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * SubTitle Color field in *Loyalty*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.subtitle_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  subtitle_color: prismic.ColorField;

  /**
   * Content Color field in *Loyalty*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.content_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_color: prismic.ColorField;

  /**
   * Icon Color field in *Loyalty*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.icon_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  icon_color: prismic.ColorField;

  /**
   * Button Text field in *Loyalty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Background Color field in *Loyalty*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.button_background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;

  /**
   * Button Text Color field in *Loyalty*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.button_text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_text_color: prismic.ColorField;

  /**
   * Slice Zone field in *Loyalty*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LoyaltyDocumentDataSlicesSlice> /**
   * Meta Title field in *Loyalty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: loyalty.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Loyalty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: loyalty.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Loyalty*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Loyalty document from Prismic
 *
 * - **API ID**: `loyalty`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LoyaltyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LoyaltyDocumentData>,
    "loyalty",
    Lang
  >;

/**
 * Content for Loyalty card documents
 */
interface LoyaltyCardDocumentData {
  /**
   * Icon field in *Loyalty card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty_card.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Loyalty card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty_card.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Loyalty card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty_card.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Content field in *Loyalty card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty_card.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Loyalty card document from Prismic
 *
 * - **API ID**: `loyalty_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LoyaltyCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LoyaltyCardDocumentData>,
    "loyalty_card",
    Lang
  >;

/**
 * Item in *Navigation → Nav Items*
 */
export interface NavigationDocumentDataNavItemsItem {
  /**
   * Nav Item Image field in *Navigation → Nav Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_items[].nav_item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  nav_item_image: prismic.ImageField<never>;

  /**
   * Nav Link field in *Navigation → Nav Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_items[].nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Navigation → Nav Actions*
 */
export interface NavigationDocumentDataNavActionsItem {
  /**
   * Action Image field in *Navigation → Nav Actions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_actions[].action_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  action_image: prismic.ImageField<never>;

  /**
   * Action Link field in *Navigation → Nav Actions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_actions[].action_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  action_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Hide Module field in *Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navigation.hide_module
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Nav Items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_items: prismic.GroupField<Simplify<NavigationDocumentDataNavItemsItem>>;

  /**
   * Nav Logo field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  nav_logo: prismic.ImageField<never>;

  /**
   * Nav Actions field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_actions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_actions: prismic.GroupField<
    Simplify<NavigationDocumentDataNavActionsItem>
  >;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type ProductsDocumentDataSlicesSlice =
  | ProductDetailsSlice
  | TestimonialsSlice
  | NewsLetterSlice
  | HeroBannerSlice;

/**
 * Content for Products documents
 */
interface ProductsDocumentData {
  /**
   * Slice Zone field in *Products*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: products.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductsDocumentDataSlicesSlice> /**
   * Meta Title field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: products.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: products.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

/**
 * Item in *Settings → Social Media*
 */
export interface SettingsDocumentDataSocialMediaItem {
  /**
   * Social Icon field in *Settings → Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>;

  /**
   * Social Link field in *Settings → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Social Media field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialMediaItem>
  >;

  /**
   * demo image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.demo_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  demo_image: prismic.ImageField<never>;

  /**
   * Copyright Content field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  copyright_content: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Terms Conditions field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.terms_conditions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  terms_conditions: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Privacy Policy field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_policy: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type ShopDocumentDataSlicesSlice =
  | PromotionalBannerSlice
  | HeroBannerSlice
  | NewsLetterSlice;

type ShopDocumentDataSlices2Slice = StyleSlice;

/**
 * Content for Shop documents
 */
interface ShopDocumentData {
  /**
   * Slice Zone field in *Shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ShopDocumentDataSlicesSlice> /**
   * Meta Title field in *Shop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: shop.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Shop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: shop.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Shop*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *Shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices2[]
   * - **Tab**: Style
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<ShopDocumentDataSlices2Slice>;
}

/**
 * Shop document from Prismic
 *
 * - **API ID**: `shop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShopDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ShopDocumentData>, "shop", Lang>;

type TestDocumentDataSlicesSlice = HeroBannerSlice;

/**
 * Content for test documents
 */
interface TestDocumentData {
  /**
   * Slice Zone field in *test*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestDocumentDataSlicesSlice> /**
   * Meta Title field in *test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: test.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: test.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TestDocumentData>, "test", Lang>;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Rating Count field in *Testimonial*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.rating_count
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating_count: prismic.NumberField;

  /**
   * Review Content field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.review_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  review_content: prismic.RichTextField;

  /**
   * Author field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | AgeVerificationDocument
  | AnnouncementBarDocument
  | BlogDocument
  | BlogPostDocument
  | ContainerDocument
  | FooterDocument
  | HomeDocument
  | LoyaltyDocument
  | LoyaltyCardDocument
  | NavigationDocument
  | ProductsDocument
  | SettingsDocument
  | ShopDocument
  | TestDocument
  | TestimonialDocument;

/**
 * Item in *BlogCards → Default → Primary → Blog Relation*
 */
export interface BlogCardsSliceDefaultPrimaryBlogRelationItem {
  /**
   * Blog Rel field in *BlogCards → Default → Primary → Blog Relation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_cards.default.primary.blog_relation[].blog_rel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blog_rel: prismic.ContentRelationshipField<"blog_post">;
}

/**
 * Primary content in *BlogCards → Default → Primary*
 */
export interface BlogCardsSliceDefaultPrimary {
  /**
   * Blog Relation field in *BlogCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_cards.default.primary.blog_relation[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  blog_relation: prismic.GroupField<
    Simplify<BlogCardsSliceDefaultPrimaryBlogRelationItem>
  >;
}

/**
 * Default variation for BlogCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogCards*
 */
type BlogCardsSliceVariation = BlogCardsSliceDefault;

/**
 * BlogCards Shared Slice
 *
 * - **API ID**: `blog_cards`
 * - **Description**: BlogCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogCardsSlice = prismic.SharedSlice<
  "blog_cards",
  BlogCardsSliceVariation
>;

/**
 * Primary content in *FeaturedProducts → Default → Primary*
 */
export interface FeaturedProductsSliceDefaultPrimary {
  /**
   * Hide Module field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: featured_products.default.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Sub Title field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * SubTitle Color field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.subtitle_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  subtitle_color: prismic.ColorField;

  /**
   * Title field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Title Color field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Background Color field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Button Text field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Background Color field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.button_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;

  /**
   * Button Text Color field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.button_text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_text_color: prismic.ColorField;
}

/**
 * Default variation for FeaturedProducts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProducts*
 */
type FeaturedProductsSliceVariation = FeaturedProductsSliceDefault;

/**
 * FeaturedProducts Shared Slice
 *
 * - **API ID**: `featured_products`
 * - **Description**: FeaturedProducts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSlice = prismic.SharedSlice<
  "featured_products",
  FeaturedProductsSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Hero Image field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Heading field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading Prefix field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.sub_heading_prefix
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_heading_prefix: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Sub Heading field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Sub Heading Prefix 2 field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.sub_heading_prefix_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_heading_prefix_2: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Item in *IconWIthText → Default → Primary → Strengths*
 */
export interface IconWIthTextSliceDefaultPrimaryStrengthsItem {
  /**
   * Icon  field in *IconWIthText → Default → Primary → Strengths*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.strengths[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *IconWIthText → Default → Primary → Strengths*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.strengths[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *IconWIthText → Default → Primary → Strengths*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.strengths[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *IconWIthText → Default → Primary*
 */
export interface IconWIthTextSliceDefaultPrimary {
  /**
   * Title field in *IconWIthText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Strengths field in *IconWIthText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.strengths[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  strengths: prismic.GroupField<
    Simplify<IconWIthTextSliceDefaultPrimaryStrengthsItem>
  >;

  /**
   * Icon Bg Color field in *IconWIthText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.icon_bg_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  icon_bg_color: prismic.ColorField;

  /**
   * Section Bg Color field in *IconWIthText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_text.default.primary.section_bg_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_bg_color: prismic.ColorField;

  /**
   * Container field in *IconWIthText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: icon_w_ith_text.default.primary.container
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  container: prismic.BooleanField;
}

/**
 * Default variation for IconWIthText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconWIthTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconWIthTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconWIthText*
 */
type IconWIthTextSliceVariation = IconWIthTextSliceDefault;

/**
 * IconWIthText Shared Slice
 *
 * - **API ID**: `icon_w_ith_text`
 * - **Description**: IconWIthText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconWIthTextSlice = prismic.SharedSlice<
  "icon_w_ith_text",
  IconWIthTextSliceVariation
>;

/**
 * Item in *ImageGallery → Default → Primary → ImageGrid*
 */
export interface ImageGallerySliceDefaultPrimaryImagegridItem {
  /**
   * Gallery Image field in *ImageGallery → Default → Primary → ImageGrid*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.imagegrid[].gallery_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gallery_image: prismic.ImageField<never>;

  /**
   * Founder Name field in *ImageGallery → Default → Primary → ImageGrid*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.imagegrid[].founder_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_name: prismic.KeyTextField;
}

/**
 * Primary content in *ImageGallery → Default → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
  /**
   * Hide Module field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_gallery.default.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Title field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * ImageGrid field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.imagegrid[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  imagegrid: prismic.GroupField<
    Simplify<ImageGallerySliceDefaultPrimaryImagegridItem>
  >;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Primary content in *ImageWithText → Default → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Hide Module field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.default.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Image field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Color field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Text Color field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Button Background Color field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.button_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;

  /**
   * Button Text Color field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.button_text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_text_color: prismic.ColorField;

  /**
   * Image Position field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_position: prismic.SelectField<"Left" | "Right">;

  /**
   * Container field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.default.primary.container
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  container: prismic.BooleanField;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageWithText → SkewedImageWithText → Primary*
 */
export interface ImageWithTextSliceSkewedImageWithTextPrimary {
  /**
   * Hide Module field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Image field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text Above Image field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.text_above_image
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_above_image: prismic.RichTextField;

  /**
   * Text Above Image Color field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.text_above_image_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_above_image_color: prismic.ColorField;

  /**
   * Title field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Color field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Text Color field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Button Background Color field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.button_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;

  /**
   * Button Text Color field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.button_text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_text_color: prismic.ColorField;

  /**
   * Image Position field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.image_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_position: prismic.SelectField<"Left" | "Right">;

  /**
   * Content Alignment field in *ImageWithText → SkewedImageWithText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: image_with_text.skewedImageWithText.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_alignment: prismic.SelectField<"left" | "center" | "right", "filled">;
}

/**
 * SkewedImageWithText variation for ImageWithText Slice
 *
 * - **API ID**: `skewedImageWithText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceSkewedImageWithText =
  prismic.SharedSliceVariation<
    "skewedImageWithText",
    Simplify<ImageWithTextSliceSkewedImageWithTextPrimary>,
    never
  >;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation =
  | ImageWithTextSliceDefault
  | ImageWithTextSliceSkewedImageWithText;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Item in *LoyaltyCards → Default → Primary → Loyalty card*
 */
export interface LoyaltyCardsSliceDefaultPrimaryLoyaltyCardItem {
  /**
   * Loyalty card field in *LoyaltyCards → Default → Primary → Loyalty card*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty_cards.default.primary.loyalty_card[].loyalty_card
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  loyalty_card: prismic.ContentRelationshipField<"loyalty_card">;
}

/**
 * Primary content in *LoyaltyCards → Default → Primary*
 */
export interface LoyaltyCardsSliceDefaultPrimary {
  /**
   * Loyalty card field in *LoyaltyCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: loyalty_cards.default.primary.loyalty_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  loyalty_card: prismic.GroupField<
    Simplify<LoyaltyCardsSliceDefaultPrimaryLoyaltyCardItem>
  >;
}

/**
 * Default variation for LoyaltyCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LoyaltyCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LoyaltyCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LoyaltyCards*
 */
type LoyaltyCardsSliceVariation = LoyaltyCardsSliceDefault;

/**
 * LoyaltyCards Shared Slice
 *
 * - **API ID**: `loyalty_cards`
 * - **Description**: LoyaltyCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LoyaltyCardsSlice = prismic.SharedSlice<
  "loyalty_cards",
  LoyaltyCardsSliceVariation
>;

/**
 * Primary content in *NewsLetter → Default → Primary*
 */
export interface NewsLetterSliceDefaultPrimary {
  /**
   * Hide Module field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: news_letter.default.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * PreHeading field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.preheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  preheading: prismic.KeyTextField;

  /**
   * PreHeading Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.preheading_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  preheading_color: prismic.ColorField;

  /**
   * Title field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Title Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Description field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Description Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.description_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  description_color: prismic.ColorField;

  /**
   * Placeholder Text field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.placeholder_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder_text: prismic.KeyTextField;

  /**
   * Button Text field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Background Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.button_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;

  /**
   * Background Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Border Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.border_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  border_color: prismic.ColorField;

  /**
   * Background Image field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Button Text Color field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.button_text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_text_color: prismic.ColorField;
}

/**
 * Default variation for NewsLetter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsLetterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsLetterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsLetter*
 */
type NewsLetterSliceVariation = NewsLetterSliceDefault;

/**
 * NewsLetter Shared Slice
 *
 * - **API ID**: `news_letter`
 * - **Description**: NewsLetter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsLetterSlice = prismic.SharedSlice<
  "news_letter",
  NewsLetterSliceVariation
>;

/**
 * Primary content in *ProductDetails → Default → Primary*
 */
export interface ProductDetailsSliceDefaultPrimary {
  /**
   * Title field in *ProductDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_details.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ProductDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductDetailsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductDetails*
 */
type ProductDetailsSliceVariation = ProductDetailsSliceDefault;

/**
 * ProductDetails Shared Slice
 *
 * - **API ID**: `product_details`
 * - **Description**: ProductDetails
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDetailsSlice = prismic.SharedSlice<
  "product_details",
  ProductDetailsSliceVariation
>;

/**
 * Item in *PromotionalBanner → Default → Primary → Promotional Items*
 */
export interface PromotionalBannerSliceDefaultPrimaryPromotionalItemsItem {
  /**
   * Extra Class field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].extra_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  extra_class: prismic.KeyTextField;

  /**
   * Image field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Percentage Offer field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].percentage_offer
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  percentage_offer: prismic.NumberField;

  /**
   * Button Position field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].button_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Hover Bg Color field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].hover_bg_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  hover_bg_color: prismic.ColorField;

  /**
   * Button Link field in *PromotionalBanner → Default → Primary → Promotional Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *PromotionalBanner → Default → Primary*
 */
export interface PromotionalBannerSliceDefaultPrimary {
  /**
   * Hide Module field in *PromotionalBanner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: promotional_banner.default.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Container field in *PromotionalBanner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: promotional_banner.default.primary.container
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  container: prismic.BooleanField;

  /**
   * Background Image field in *PromotionalBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *PromotionalBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *PromotionalBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Promotional Items field in *PromotionalBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: promotional_banner.default.primary.promotional_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  promotional_items: prismic.GroupField<
    Simplify<PromotionalBannerSliceDefaultPrimaryPromotionalItemsItem>
  >;
}

/**
 * Default variation for PromotionalBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionalBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PromotionalBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PromotionalBanner*
 */
type PromotionalBannerSliceVariation = PromotionalBannerSliceDefault;

/**
 * PromotionalBanner Shared Slice
 *
 * - **API ID**: `promotional_banner`
 * - **Description**: PromotionalBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionalBannerSlice = prismic.SharedSlice<
  "promotional_banner",
  PromotionalBannerSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → Slides*
 */
export interface SliderSliceDefaultPrimarySlidesItem {
  /**
   * Slide Image field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].slide_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slide_image: prismic.ImageField<never>;

  /**
   * Video field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Slide Text field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].slide_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slide_text: prismic.TitleField;

  /**
   * Slide Subtext field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].slide_subtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slide_subtext: prismic.RichTextField;

  /**
   * Slide Text 2 field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].slide_text_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slide_text_two: prismic.TitleField;

  /**
   * Video Link field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Video Thumbnail field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].video_thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_thumbnail: prismic.ImageField<never>;

  /**
   * Video Button Text field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].video_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_button_text: prismic.KeyTextField;

  /**
   * Text Animation field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: slider.default.primary.slides[].text_animation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_animation: prismic.BooleanField;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Hide Module field in *Slider → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: slider.default.primary.hide_module
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide_module: prismic.BooleanField;

  /**
   * Extra Class field in *Slider → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.extra_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  extra_class: prismic.KeyTextField;

  /**
   * Slides field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slides: prismic.GroupField<Simplify<SliderSliceDefaultPrimarySlidesItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Primary content in *Style → Default → Primary*
 */
export interface StyleSliceDefaultPrimary {
  /**
   * Extra Class field in *Style → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: style.default.primary.extra_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  extra_class: prismic.KeyTextField;

  /**
   * Clear Margin field in *Style → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: style.default.primary.clear_margin
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  clear_margin: prismic.SelectField<"top" | "bottom" | "left" | "right">;

  /**
   * Continer field in *Style → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: style.default.primary.continer
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  continer: prismic.BooleanField;
}

/**
 * Default variation for Style Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StyleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StyleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Style*
 */
type StyleSliceVariation = StyleSliceDefault;

/**
 * Style Shared Slice
 *
 * - **API ID**: `style`
 * - **Description**: Style
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StyleSlice = prismic.SharedSlice<"style", StyleSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → TestimonialCards*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialcardsItem {
  /**
   * Testimonial field in *Testimonials → Default → Primary → TestimonialCards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialcards[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonial">;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * TestimonialCards field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialcards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonialcards: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialcardsItem>
  >;

  /**
   * Button Link field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AgeVerificationDocument,
      AgeVerificationDocumentData,
      AnnouncementBarDocument,
      AnnouncementBarDocumentData,
      AnnouncementBarDocumentDataItemsItem,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      ContainerDocument,
      ContainerDocumentData,
      ContainerDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterCategoriesItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LoyaltyDocument,
      LoyaltyDocumentData,
      LoyaltyDocumentDataSlicesSlice,
      LoyaltyCardDocument,
      LoyaltyCardDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavItemsItem,
      NavigationDocumentDataNavActionsItem,
      ProductsDocument,
      ProductsDocumentData,
      ProductsDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialMediaItem,
      ShopDocument,
      ShopDocumentData,
      ShopDocumentDataSlicesSlice,
      ShopDocumentDataSlices2Slice,
      TestDocument,
      TestDocumentData,
      TestDocumentDataSlicesSlice,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      BlogCardsSlice,
      BlogCardsSliceDefaultPrimaryBlogRelationItem,
      BlogCardsSliceDefaultPrimary,
      BlogCardsSliceVariation,
      BlogCardsSliceDefault,
      FeaturedProductsSlice,
      FeaturedProductsSliceDefaultPrimary,
      FeaturedProductsSliceVariation,
      FeaturedProductsSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      IconWIthTextSlice,
      IconWIthTextSliceDefaultPrimaryStrengthsItem,
      IconWIthTextSliceDefaultPrimary,
      IconWIthTextSliceVariation,
      IconWIthTextSliceDefault,
      ImageGallerySlice,
      ImageGallerySliceDefaultPrimaryImagegridItem,
      ImageGallerySliceDefaultPrimary,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceSkewedImageWithTextPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      ImageWithTextSliceSkewedImageWithText,
      LoyaltyCardsSlice,
      LoyaltyCardsSliceDefaultPrimaryLoyaltyCardItem,
      LoyaltyCardsSliceDefaultPrimary,
      LoyaltyCardsSliceVariation,
      LoyaltyCardsSliceDefault,
      NewsLetterSlice,
      NewsLetterSliceDefaultPrimary,
      NewsLetterSliceVariation,
      NewsLetterSliceDefault,
      ProductDetailsSlice,
      ProductDetailsSliceDefaultPrimary,
      ProductDetailsSliceVariation,
      ProductDetailsSliceDefault,
      PromotionalBannerSlice,
      PromotionalBannerSliceDefaultPrimaryPromotionalItemsItem,
      PromotionalBannerSliceDefaultPrimary,
      PromotionalBannerSliceVariation,
      PromotionalBannerSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimarySlidesItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
      StyleSlice,
      StyleSliceDefaultPrimary,
      StyleSliceVariation,
      StyleSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialcardsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
