// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_cards: dynamic(() => import("./BlogCards")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  news_letter: dynamic(() => import("./NewsLetter")),
  promotional_banner: dynamic(() => import("./PromotionalBanner")),
  slider: dynamic(() => import("./Slider")),
  style: dynamic(() => import("./Style")),
};
