import { Geist, Geist_Mono, Open_Sans } from "next/font/google";

import "./globals.css";
import { PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import Announcement from "./components/Announcement";
import AgeVerification from "./components/AgeVarification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerData = async () => {
  let client = createClient();
  const response = await client.getByUID("navigation", "navigation-uid");
  const announcementBar = await client.getByUID(
    "announcement_bar",
    "announcement-bar-uid"
  );
  const AgeVarification = await client.getByUID(
    "age_verification",
    "age_verification-uid"
  );
  return { response, announcementBar, AgeVarification };
};

export default async function RootLayout({ children }) {
  const { response, announcementBar, AgeVarification } = await headerData();
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} antialiased scroll-smooth`}
      >
        <AgeVerification data={AgeVarification.data} />
        <Announcement data={announcementBar.data} />
        <Navigation data={response.data} />
        {children}
        <Footer />
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  );
}
